# Generated by Django 5.1.1 on 2024-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
