# Generated by Django 5.1.1 on 2024-09-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_processor', '0002_processedemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedEmail',
        ),
    ]
