# Generated by Django 5.1.1 on 2024-09-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_processor', '0004_application_academic_qualification_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_quality_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
