# Generated by Django 5.1.1 on 2024-09-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_processor', '0005_application_experience_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='academic_qualification_match',
            new_name='analysis',
        ),
        migrations.RemoveField(
            model_name='application',
            name='achievements_match',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experience_summary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='industry_match',
        ),
        migrations.RemoveField(
            model_name='application',
            name='key_skills_match',
        ),
        migrations.RemoveField(
            model_name='application',
            name='location_match',
        ),
        migrations.RemoveField(
            model_name='application',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='responsibilities_match',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume_quality',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume_quality_notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='years_of_experience_match',
        ),
    ]
