# Generated by Django 5.1.1 on 2024-09-30 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('job_description', models.TextField()),
                ('gemini_response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_processor_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
