# Generated by Django 5.1.1 on 2024-09-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_processor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
